#ifndef VITARPS5_ERROR_CODES_H
#define VITARPS5_ERROR_CODES_H

// Comprehensive error code system based on Chiaki/Vitaki
typedef enum {
  // Success
  VITARPS5_ERR_SUCCESS = 0,

  // General errors
  VITARPS5_ERR_UNKNOWN = 1,
  VITARPS5_ERR_MEMORY = 2,
  VITARPS5_ERR_OVERFLOW = 3,
  VITARPS5_ERR_INVALID_DATA = 4,
  VITARPS5_ERR_INVALID_PARAM = 5,
  VITARPS5_ERR_INVALID_STATE = 6,
  VITARPS5_ERR_THREAD = 7,
  VITARPS5_ERR_TIMEOUT = 8,
  VITARPS5_ERR_CANCELED = 9,
  VITARPS5_ERR_IN_PROGRESS = 10,
  VITARPS5_ERR_BUF_TOO_SMALL = 11,

  // Network errors
  VITARPS5_ERR_NETWORK = 20,
  VITARPS5_ERR_PARSE_ADDR = 21,
  VITARPS5_ERR_CONNECTION_REFUSED = 22,
  VITARPS5_ERR_HOST_DOWN = 23,
  VITARPS5_ERR_HOST_UNREACH = 24,
  VITARPS5_ERR_DISCONNECTED = 25,
  VITARPS5_ERR_SOCKET_FAILED = 26,
  VITARPS5_ERR_BIND_FAILED = 27,
  VITARPS5_ERR_CONNECT_FAILED = 28,

  // PS5-specific errors
  VITARPS5_ERR_VERSION_MISMATCH = 30,
  VITARPS5_ERR_AUTH_FAILED = 31,
  VITARPS5_ERR_INVALID_RESPONSE = 32,
  VITARPS5_ERR_CRYPTO = 33,
  VITARPS5_ERR_REGISTRATION_FAILED = 34,
  VITARPS5_ERR_CONSOLE_NOT_REGISTERED = 35,
  VITARPS5_ERR_PSN_ACCOUNT_REQUIRED = 36,
  VITARPS5_ERR_INVALID_CREDENTIALS = 37,

  // Service availability errors
  VITARPS5_ERR_SERVICE_NOT_READY = 40,
  VITARPS5_ERR_CONSOLE_IN_STANDBY = 41,
  VITARPS5_ERR_CONSOLE_OFFLINE = 42,
  VITARPS5_ERR_REMOTE_PLAY_DISABLED = 43,
  VITARPS5_ERR_WAKE_FAILED = 44,

  // Session errors
  VITARPS5_ERR_SESSION_CREATE_FAILED = 50,
  VITARPS5_ERR_SESSION_NOT_FOUND = 51,
  VITARPS5_ERR_SESSION_ALREADY_EXISTS = 52,

  // Video/Audio errors
  VITARPS5_ERR_VIDEO_DECODER = 60,
  VITARPS5_ERR_AUDIO_DECODER = 61,
  VITARPS5_ERR_RENDERER = 62,

  // Discovery errors
  VITARPS5_ERR_DISCOVERY_FAILED = 70,
  VITARPS5_ERR_DISCOVERY_TIMEOUT = 71,

} VitaRPS5ErrorCode;

// Note: ChiakiErrorCode is defined in chiaki/chiaki_common.h

// Console state enum (from Chiaki discovery)
typedef enum {
  CONSOLE_STATE_UNKNOWN = 0,
  CONSOLE_STATE_READY = 1,
  CONSOLE_STATE_STANDBY = 2,
} ConsoleState;

// Function declarations
const char* vitarps5_error_string(VitaRPS5ErrorCode error);
const char* vitarps5_error_description(VitaRPS5ErrorCode error);
const char* vitarps5_error_hint(VitaRPS5ErrorCode error);
const char* console_state_string(ConsoleState state);
// Note: chiaki_to_vitarps5_error is defined in chiaki_integration.h with
// different signature

#endif  // VITARPS5_ERROR_CODES_H